---
development:
  cloud_name: funlife
  api_key: '221816386951751'
  api_secret: p0HsqkrLaNZpg3nruhEfWl4-tuc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: funlife
  api_key: '221816386951751'
  api_secret: p0HsqkrLaNZpg3nruhEfWl4-tuc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: funlife
  api_key: '221816386951751'
  api_secret: p0HsqkrLaNZpg3nruhEfWl4-tuc
  enhance_image_tag: true
  static_image_support: false
